services:
  mysql:
    image: mysql:latest
    container_name: goticket-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: goticket
      MYSQL_USER: goticket
      MYSQL_PASSWORD: 123456
    volumes:
      - ../mysql-data/:/var/lib/mysql/
      - ./db:/docker-entrypoint-initdb.d